---
swagger: "2.0"
info:
  title: "Cars and Drivers API"
  description: "Backend REST API service implementation in Java to manage Cars and Drivers"
consumes:
  - application/json
produces:
  - application/json